# Generated by Django 2.2.19 on 2021-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('html_text', models.TextField()),
                ('description', models.TextField()),
                ('site_name', models.CharField(max_length=80)),
                ('site_url', models.TextField()),
                ('image_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DynamicHtml',
                'verbose_name_plural': 'DynamicHtml',
            },
        ),
    ]
